package com.organizee.domain.exceptions

object ExceptionMessage {
    const val EMAIL_ALREADY_IN_USE = "Email already in use"
    const val USERNAME_ALREADY_IN_USE = "Username already in use"
}